image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

users-build:
  stage: build
  script:
    gradle :gateway:classes :gateway:testClasses

users-checkStyle:
  stage: staticAnalysis
  script:
    gradle :gateway:checkstyleMain :gateway:checkStyleTest
  allow_failure: true

users-PMD:
  stage: staticAnalysis
  script:
    gradle :gateway:pmdMain :gateway:pmdTest
  allow_failure: true

users-test:
  stage: test
  script:
    - gradle :gateway:test :gateway:jacocoTestReport :gateway:pitest
    - cat gateway/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/