image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

microservice1-build:
  stage: build
  script:
    gradle :microservice1:build

microservice1-checkStyle:
  stage: staticAnalysis
  script:
    gradle :microservice1:checkstyleMain :microservice1:checkStyleTest

microservice1-PMD:
  stage: staticAnalysis
  script:
      gradle :microservice1:pmdMain :microservice1:pmdTest

microservice1-test:
  stage: test
  script:
    - gradle :microservice1:test
    - microservice1/build/reports/jacoco/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
