image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

eureka-build:
  stage: build
  script:
    gradle :eureka:classes :eureka:testClasses

eureka-checkStyle:
  stage: staticAnalysis
  script:
    gradle :eureka:checkstyleMain :eureka:checkStyleTest
  allow_failure: true

eureka-PMD:
  stage: staticAnalysis
  script:
    gradle :eureka:pmdMain :eureka:pmdTest
  allow_failure: true

eureka-test:
  stage: test
  script:
    - gradle :eureka:test :eureka:jacocoTestReport :eureka:pitest
    - cat eureka/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
