image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

student-service-post-build:
  stage: build
  script:
    gradle :student-service-post:build

student-service-post-checkStyle:
  stage: staticAnalysis
  script:
    gradle :student-service-post:checkstyleMain :student-service-post:checkStyleTest

student-service-post-PMD:
  stage: staticAnalysis
  script:
      gradle :student-service-post:pmdMain :student-service-post:pmdTest

student-service-post-test:
  stage: test
  script:
    - gradle :student-service-post:test :student-service-post:jacocoTestReport
    - cat student-service-post/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
