image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

contracts-build:
  stage: build
  script:
    gradle :contracts:classes :contracts:testClasses

contracts-checkStyle:
  stage: staticAnalysis
  script:
    gradle :contracts:checkstyleMain :contracts:checkStyleTest

contracts-PMD:
  stage: staticAnalysis
  script:
      gradle :contracts:pmdMain :contracts:pmdTest

contracts-test:
  stage: test
  script:
    - gradle :contracts:test :contracts:jacocoTestReport :contracts:pitest
    - cat contracts/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
