image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

users-build:
  stage: build
  script:
    gradle :users:build

users-checkStyle:
  stage: staticAnalysis
  script:
    gradle :users:checkstyleMain :users:checkStyleTest

users-PMD:
  stage: staticAnalysis
  script:
      gradle :users:pmdMain :users:pmdTest

users-test:
  stage: test
  script:
    - gradle :users:test :users:jacocoTestReport :users:pitest
    - cat users/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
