image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

build:
  stage: build
  script:
    gradle build

checkStyle:
  stage: staticAnalysis
  script:
    gradle checkstyleMain checkStyleTest

PMD:
  stage: staticAnalysis
  script:
      gradle pmdMain pmdTest

test:
  stage: test
  script:
    gradle test
